### PR TITLE
Fix parsing of reset and label commands when there are spaces in the label

### PR DESCRIPTION
**Pull request by stefanhaller**
According to the C code in git.git, the label is the rest of the line; there can't be comments. The example in the git-rebase man page seems to be wrong.

It is important to parse this correctly because git does actually use "reset" with a label that contains spaces: when you use "git rebase -i --rebase-merges --root", the first command in the todo file is "reset [new root]".

### CODE REVIEW

**Comment by stefanhaller** [comment]
I asked for clarification about this on the [git mailing list](https://public-inbox.org/git/db535468-c991-df18-61bd-ec312fdb5ca0@haller-berlin.de/), but didn't get a reply yet.

**Comment by stefanhaller** [comment]
There's now some discussion about this on the git mailing list, and the fix I chose might not be the best one. Please hold off merging this for now, I might change this again slightly.

**Comment by fsmiamoto** [comment]
Interesting. 
Sure, will hold it for now

**Comment by stefanhaller** [comment]
The outcome of the mailing list discussion linked to above was that it's best to stay with git's current behavior (which is to use only the first word up to the first white space for the label and ignore the rest), which means that we simply need to special-case the `[new root]` case before. I force-pushed the branch, this is good to go from my side.

If you could then also tag it with 0.0.4, that would be appreciated.

**Comment by stefanhaller** [comment]
Sorry to pester you with this, but as I have other PRs that are blocked by this, it would be great if this could be merged soon. Thanks! 🙏

**Comment by fsmiamoto** [comment]
Sorry about the delay, it should be ready to go!

**Pull request merged**
